services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - '${POCKETBASE_PORT:-8090}:8090'
    volumes:
      - ./pocketbase/pb_data:/pb/pb_data
      - ./pocketbase/pb_migrations:/pb/pb_migrations
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:8090/api/health']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    command: serve --http=0.0.0.0:8090 --dir=/pb/pb_data

  frontend:
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '${FRONTEND_PORT:-8080}:8080'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PUBLIC_POCKETBASE_URL=${PUBLIC_POCKETBASE_URL:-http://localhost:8090}
      - POCKETBASE_URL=${POCKETBASE_URL:-http://pocketbase:8090}
    command: sh -c "bun install && bun run dev -- --host 0.0.0.0 --port 8080"
    depends_on:
      pocketbase:
        condition: service_healthy
    restart: unless-stopped
